# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe6\x98\xb5\xe7\xa7\xb0')),
                ('date', models.DateField(verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('item', models.CharField(choices=[(b'0', '001---\u4f5b\u53f7\u6216\u5492\u8bed---'), (b'1', '002 \u963f\u5f25\u9640\u4f5b'), (b'2', '005 \u767e\u5b57\u660e'), (b'3', '010 \u5730\u85cf\u83e9\u8428'), (b'4', '015 \u5ea6\u6bcd\u5fc3\u5492'), (b'5', '020 \u89c2\u97f3\u5fc3\u5492'), (b'6', '025 \u91d1\u521a\u9562\u5fc3\u5492'), (b'7', '030 \u91d1\u521a\u8428\u57f5\u5fc3\u5492'), (b'8', '035 \u4e5d\u672c\u5c0a\u5fc3\u5492'), (b'9', '040 \u695e\u4e25\u5492'), (b'10', '045 \u83b2\u5e08\u5fc3\u5492'), (b'11', '050 \u5f80\u751f\u5492'), (b'12', '055 \u6587\u6b8a\u5fc3\u5492'), (b'13', '060\u5177\u5149\u4f5b\u6bcd\u5fc3\u5492'), (b'14', '300---\u7ecf\u8bba\u6216\u7948\u7977\u6587---'), (b'15', '301 \u516b\u5409\u7965\u9882'), (b'16', '310 \u5927\u81ea\u5728\u7948\u7977\u6587'), (b'17', '315 \u4e8c\u5341\u4e00\u5ea6\u6bcd\u8d5e'), (b'18', '320 \u6cd5\u738b\u5982\u610f\u5b9d\u7948\u7977\u6587'), (b'19', '325 \u91d1\u521a\u7ecf'), (b'20', '330 \u83b2\u5e08\u4e03\u53e5'), (b'21', '335 \u666e\u83b7\u6089\u5730\u7948\u7977\u6587'), (b'22', '340 \u666e\u8d24\u884c\u613f\u54c1'), (b'23', '350 \u5fc3\u7ecf'), (b'24', '500---\u5176\u4ed6---'), (b'25', '510 \u4f9b\u706f')], max_length=100, verbose_name=b'\xe7\xbb\x8f\xe5\x92\x92')),
                ('number', models.IntegerField(verbose_name=b'\xe6\x95\xb0\xe9\x87\x8f')),
            ],
        ),
    ]
